/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://2lwaolv6azgdhkfb4fzbbxzgfm.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7l6xq3ahibh7nbgz3kk22p27p4",
    "aws_cognito_identity_pool_id": "eu-west-3:27b5b1ba-79d4-4326-91a2-e100900b977e",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_gmD2gZiOo",
    "aws_user_pools_web_client_id": "5s290lr75g7qhr1akpqlm5gtf4",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "konkrete-app-storage-5d35380c172356-staging",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
